### ISSUE TITLE
Where can I find the slides of this tranining?

### ISSUE THREAD

**Issue by tisonkun** [ververica/flink-training-troubleshooting#10]
I just redirected to here from a [link](https://github.com/ververica/flink-training-troubleshooting/blob/master/slides/2019-10-07%20_%20TROUBLESHOOTING%20_%207%20OBJECT%20REUSE.pdf) said about object reused but the link is broken(404).

**Comment by NicoK** [comment]
This repository is outdated in favour of https://github.com/ververica/flink-training/.

Closing open issues...
