### ISSUE TITLE
Correct the default writerbuffer size of RocksDB

### ISSUE THREAD

**Issue by Myasuka** [ververica/flink-training-troubleshooting#5]
As [FLINK-14846](https://issues.apache.org/jira/browse/FLINK-14846) already merged, we should also fix the description in [state-manage-slide](https://github.com/ververica/flink-training-troubleshooting/blob/master/slides/2019-10-07%20_%20TROUBLESHOOTING%20_%206%20STATE%20MANAGEMENT.pdf). Change it from `4MB` to `64MB`.

**Comment by Myasuka** [comment]
@NicoK please take a look at this.

**Comment by NicoK** [comment]
This repository is outdated in favour of https://github.com/ververica/flink-training/.

Closing open issues...
